version: '3.8'
services:
  rxjs-server:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: rxjs-server
    ports:
      - 3000:3000
    volumes:
      - '.:/app'
      - '/app/node_modules'
